//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoneyManager.ManagerSevice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagerSevice.IServiceModule")]
    public interface IServiceModule {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModule/AddItemToDb", ReplyAction="http://tempuri.org/IServiceModule/AddItemToDbResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MyMoneyManager.Infrastucture.DataTransferObjects.DtoItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MyMoneyManager.Infrastucture.DataTransferObjects.ExpensesDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MyMoneyManager.Infrastucture.DataTransferObjects.DtoSetting))]
        void AddItemToDb(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModule/AddItemToDb", ReplyAction="http://tempuri.org/IServiceModule/AddItemToDbResponse")]
        System.Threading.Tasks.Task AddItemToDbAsync(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModule/DeleteItemFromDb", ReplyAction="http://tempuri.org/IServiceModule/DeleteItemFromDbResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MyMoneyManager.Infrastucture.DataTransferObjects.DtoItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MyMoneyManager.Infrastucture.DataTransferObjects.ExpensesDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MyMoneyManager.Infrastucture.DataTransferObjects.DtoSetting))]
        void DeleteItemFromDb(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModule/DeleteItemFromDb", ReplyAction="http://tempuri.org/IServiceModule/DeleteItemFromDbResponse")]
        System.Threading.Tasks.Task DeleteItemFromDbAsync(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModule/EditItemInDb", ReplyAction="http://tempuri.org/IServiceModule/EditItemInDbResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MyMoneyManager.Infrastucture.DataTransferObjects.DtoItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MyMoneyManager.Infrastucture.DataTransferObjects.ExpensesDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MyMoneyManager.Infrastucture.DataTransferObjects.DtoSetting))]
        void EditItemInDb(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModule/EditItemInDb", ReplyAction="http://tempuri.org/IServiceModule/EditItemInDbResponse")]
        System.Threading.Tasks.Task EditItemInDbAsync(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModule/GetItemsFromDb", ReplyAction="http://tempuri.org/IServiceModule/GetItemsFromDbResponse")]
        MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject[] GetItemsFromDb(int requestId, System.DateTime time1, System.DateTime time2, double value1, double value2, string comment, byte expType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModule/GetItemsFromDb", ReplyAction="http://tempuri.org/IServiceModule/GetItemsFromDbResponse")]
        System.Threading.Tasks.Task<MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject[]> GetItemsFromDbAsync(int requestId, System.DateTime time1, System.DateTime time2, double value1, double value2, string comment, byte expType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceModuleChannel : MyMoneyManager.ManagerSevice.IServiceModule, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceModuleClient : System.ServiceModel.ClientBase<MyMoneyManager.ManagerSevice.IServiceModule>, MyMoneyManager.ManagerSevice.IServiceModule {
        
        public ServiceModuleClient() {
        }
        
        public ServiceModuleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceModuleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceModuleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceModuleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddItemToDb(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item) {
            base.Channel.AddItemToDb(item);
        }
        
        public System.Threading.Tasks.Task AddItemToDbAsync(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item) {
            return base.Channel.AddItemToDbAsync(item);
        }
        
        public void DeleteItemFromDb(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item) {
            base.Channel.DeleteItemFromDb(item);
        }
        
        public System.Threading.Tasks.Task DeleteItemFromDbAsync(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item) {
            return base.Channel.DeleteItemFromDbAsync(item);
        }
        
        public void EditItemInDb(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item) {
            base.Channel.EditItemInDb(item);
        }
        
        public System.Threading.Tasks.Task EditItemInDbAsync(MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject item) {
            return base.Channel.EditItemInDbAsync(item);
        }
        
        public MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject[] GetItemsFromDb(int requestId, System.DateTime time1, System.DateTime time2, double value1, double value2, string comment, byte expType) {
            return base.Channel.GetItemsFromDb(requestId, time1, time2, value1, value2, comment, expType);
        }
        
        public System.Threading.Tasks.Task<MyMoneyManager.Infrastucture.DataTransferObjects.DtoObject[]> GetItemsFromDbAsync(int requestId, System.DateTime time1, System.DateTime time2, double value1, double value2, string comment, byte expType) {
            return base.Channel.GetItemsFromDbAsync(requestId, time1, time2, value1, value2, comment, expType);
        }
    }
}
